apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-ms
  template:
    metadata:
      labels:
        app: frontend-ms
    spec:
      containers:
      - name: frontend-ms
        image: adrian4096/prpo-app-frontend:${TAG}
        ports:
        - containerPort: 8000
        env:
        - name: URNIK_URL
          value: "http://api.fritime.computers.si"
        - name: USERS_URL
          value: "http://api.fritime.computers.si/auth"
        - name: BOOL_URL
          value: "http://api.fritime.computers.si/bool"
        - name: KOSILO_URL
          value: "http://api.fritime.computers.si/kosilo"
        - name: VREME_API
          value: "http://api.fritime.computers.si/vreme"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-ms
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: frontend-ms
