apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prpo-ingress
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: user-managment-ms
            port:
              number: 80
      - path: /kosilo
        pathType: Prefix
        backend:
          service:
            name: kosilo-ms
            port:
              number: 80
      - path: /bool
        pathType: Prefix
        backend:
          service:
            name: boolean-ms
            port:
              number: 80
      - path: /optimizacije
        pathType: Prefix
        backend:
          service:
            name: optimizator-ms
            port:
              number: 80
      - path: /urniki
        pathType: Prefix
        backend:
          service:
            name: event-view-ms
            port:
              number: 80
      - path: /podatki
        pathType: Prefix
        backend:
          service:
            name: ical-ms
            port:
              number: 80
      - path: /vremena
        pathType: Prefix
        backend:
          service:
            name: weather-ms
            port:
              number: 80
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: frontend-ms
            port:
              number: 80
