apiVersion: apps/v1
kind: Deployment
metadata:
  name: kosilo-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kosilo-ms
  template:
    metadata:
      labels:
        app: kosilo-ms
    spec:
      containers:
      - name: kosilo-ms
        image: adrian4096/prpo-app-kosilo:${TAG}
        ports:
        - containerPort: 8000
        env:
        - name: EV_URL
          value: "http://event-view-ms"
        - name: BOOL_URL
          value: "http://boolean-ms"
        livenessProbe:
          httpGet:
            path: /kosilo/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /kosilo/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: kosilo-ms
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: kosilo-ms
