apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimizator-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: optimizator-ms
  template:
    metadata:
      labels:
        app: optimizator-ms
    spec:
      containers:
      - name: optimizator-ms
        image: adrian4096/prpo-app-optimizator:${TAG}
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /optimizacije/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /optimizacije/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: optimizator-ms
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: optimizator-ms
