apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-ms
  template:
    metadata:
      labels:
        app: weather-ms
    spec:
      containers:
      - name: weather-ms
        image: adrian4096/prpo-app-weather:${TAG}
        ports:
        - containerPort: 8000
        env:
        - name: OPENWEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: openweather-secrets
              key: openweather-secret
        livenessProbe:
          httpGet:
            path: /vreme/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /vreme/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: weather-ms
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: weather-ms
